<?php

namespace AppBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
        public function listing($age = 100) 
      {//la methode personnalisée listing requiert un argument dont la valeur par défaut
        //est 100, cet argument est ensuite utilisé dans la requete DQL
               // requête DQL (Doctrine Query Langage,très proche du langage SQL) personnalisée, voir fichier Player.Controller.php
             
                return $this
                ->getEntityManager()
                ->createQuery(' 
                    SELECT p 
                    FROM AppBundle:Player p 
                    WHERE p.age < :age 
                    ORDER BY p.nom ASC')
                ->setParameter('age', 100)
                ->getResult(); //tjrs la dernière opération
                    /*')->setParameter('age', $request->get('ageLimit')); //requete à la carte issue de l'info client*/
            }   
}
